#!/usr/bin/env bash
# Run vitest with Node 22+ for SQLite support

exec node \
  --dns-result-order=ipv4first \
  --experimental-sqlite \
  --disable-warning=ExperimentalWarning \
  node_modules/.bin/vitest "$@"